version: '3'

services:
    web:
        build: .
        command: python e_project/manage.py runserver 0.0.0.0:4500
        volumes:
            - .:/code
        ports:
            - "4500:4500"
        depends_on:
            - postgres
    db:
        image: postgres
    # postgres pgadmin capabilities 
    postgres:
        image: postgres
        hostname: postgres
        ports:
            - "6543:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: TEST_SM
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped

volumes:
  postgres-data: