version: '3'

services:
    web:
        build: .
        command: python e_project/manage.py runserver 0.0.0.0:4500
        volumes:
            - .:/code
        ports:
            - "4500:4500"
        depends_on:
            - db
    db:
        image: postgres