# Generated by Django 2.2.2 on 2019-06-19 10:53

from django.db import migrations, models
import e_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('price', models.FloatField(default=None)),
                ('file', models.ImageField(upload_to=e_app.models.uploadFile)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_id', models.CharField(max_length=100)),
                ('total_paid', models.FloatField(default=None)),
                ('total_tax', models.FloatField(default=None, null=True)),
                ('total_discount', models.FloatField(default=None, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete='models.CASCADE', to='e_app.Users')),
                ('product_id', models.ForeignKey(on_delete='models.CASCADE', to='e_app.Products')),
            ],
        ),
        migrations.CreateModel(
            name='AddCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=None, max_length=100)),
                ('product_price', models.FloatField(default=None)),
                ('number_of_items', models.IntegerField(default=None)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete='models.CASCADE', to='e_app.Users')),
                ('product_id', models.ForeignKey(on_delete='models.CASCADE', to='e_app.Products')),
            ],
        ),
    ]
